/// Flutter icons myicon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  myicon
///      fonts:
///       - asset: fonts/myicon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class myicon {
  myicon._();

  static const _kFontFam = 'myicon';
  static const String? _kFontPkg = null;

  static const IconData manager_knife =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recipe_knife =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard_knife =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
