// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWtVp9BAZeHTgDvb81lOJqE3oFVVom7DM',
    appId: '1:428922308220:web:8c9036da81c359657febf9',
    messagingSenderId: '428922308220',
    projectId: 'instructflow',
    authDomain: 'instructflow.firebaseapp.com',
    databaseURL:
        'https://instructflow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'instructflow.appspot.com',
    measurementId: 'G-E5HVGS53WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjec6lH6fVM77XmJMXd266h6vQQiOhRBE',
    appId: '1:428922308220:android:665c8673d10c80b07febf9',
    messagingSenderId: '428922308220',
    projectId: 'instructflow',
    databaseURL:
        'https://instructflow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'instructflow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwPlGXeX1yLqOlpxSG89Yoelww9VDXeUo',
    appId: '1:428922308220:ios:a1d75f8f06ad925f7febf9',
    messagingSenderId: '428922308220',
    projectId: 'instructflow',
    databaseURL:
        'https://instructflow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'instructflow.appspot.com',
    iosBundleId: 'com.franklyfrank.instructflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwPlGXeX1yLqOlpxSG89Yoelww9VDXeUo',
    appId: '1:428922308220:ios:325a21394bae682d7febf9',
    messagingSenderId: '428922308220',
    projectId: 'instructflow',
    databaseURL:
        'https://instructflow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'instructflow.appspot.com',
    iosBundleId: 'com.example.instructflow.RunnerTests',
  );
}
